name: Shopify Lighthouse CI
on:
    push:
        branches:
        - main
jobs:
  echo:
        runs-on: ubuntu-latest
        steps:
        - name: Echo
          run: echo "Hello, world!,token ${{ secrets.SHOP_ACCESS_TOKEN }}, store ${{ secrets.SHOP_STORE }}, password ${{ secrets.SHOP_PASSWORD }}"  
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lighthouse
      uses: shopify/lighthouse-ci-action@v1
      with:
        access_token: ${{ secrets.SHOP_ACCESS_TOKEN }}
        store: ${{ secrets.SHOP_STORE }}
        password: ${{ secrets.SHOP_PASSWORD }}
    